version: '3.8'
services:
  api:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/vuln-scanner/backend

  ui:
    build: ./frontend
    ports:
      - "3000:5173"
    volumes:
      - ./frontend:/vuln-scanner/frontend

  mongodb:
    image: mongo
    ports:
      - "27010:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
