version: '3.8'
services:
  api:
    build: ./backend
    ports:
      - "5005:5000"
    volumes:
      - ./backend:/vuln-scanner/backend

  ui:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/vuln-scanner/frontend

  mongodb:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
